# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101uopALaDPfFpbkfROZLrWshiGtOeGLx
"""
from flask import Flask, request, jsonify
import joblib
from flask_cors import CORS

# Load model dan vectorizer
model = joblib.load('Hate Speech Classifier.joblib')
vectorizer = joblib.load('Hate Speech TF-IDF Vectorizer.joblib')

app = Flask(__name__)
CORS(app)

@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()
    text = data['text']
    vec = vectorizer.transform([text])
    prediction = model.predict(vec)[0]
    label = "hate" if prediction == 1 else "non-hate"
    return jsonify({"result": label})

if __name__ == '__main__':
    app.run(debug=True)

"""The error `ModuleNotFoundError: No module named 'flask_cors'` occurs because the `flask_cors` library is not installed. The code requires this library to enable Cross-Origin Resource Sharing (CORS) for your Flask application, which allows your API to receive requests from different origins (like a Chrome extension).

The fix is to install the library using `!pip install flask-cors`. I've added a code cell above to do this. After running that cell, you should be able to run your original code cell without this error.
"""